# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use versions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

stages:
  - build_dependencies
  - build
  - test
  - deploy

build_deps_gcc13:
  stage: build_dependencies
  image: gcc:13
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - conan install . --build missing
    - conan install . --build missing --s build_type=Debug
    - conan upload boost/* -r cps-artifactory --all
    - conan upload gtest/* -r cps-artifactory --all
    - conan upload redboltz-mqtt_cpp/* -r cps-artifactory --all
    - conan upload nlohmann_json/* -r cps-artifactory --all
  only:
      refs:
        - updateDependecies

build_deps_gcc12:
  stage: build_dependencies
  image: gcc:12
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - conan install . --build missing
    - conan install . --build missing --s build_type=Debug
    - conan upload boost/* -r cps-artifactory --all
    - conan upload gtest/* -r cps-artifactory --all
    - conan upload redboltz-mqtt_cpp/* -r cps-artifactory --all
    - conan upload nlohmann_json/* -r cps-artifactory --all
  only:
      refs:
        - updateDependecies

build_deps_gcc11:
  stage: build_dependencies
  image: gcc:11
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - conan install . --build missing
    - conan install . --build missing --s build_type=Debug
    - conan upload boost/* -r cps-artifactory --all
    - conan upload gtest/* -r cps-artifactory --all
    - conan upload redboltz-mqtt_cpp/* -r cps-artifactory --all
    - conan upload nlohmann_json/* -r cps-artifactory --all
  only:
      refs:
        - updateDependecies

build_deps_gcc10:
  stage: build_dependencies
  image: gcc:10
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - conan install . --build missing
    - conan install . --build missing --s build_type=Debug
    - conan upload boost/* -r cps-artifactory --all
    - conan upload gtest/* -r cps-artifactory --all
    - conan upload redboltz-mqtt_cpp/* -r cps-artifactory --all
    - conan upload nlohmann_json/* -r cps-artifactory --all
  only:
      refs:
        - updateDependecies


build_deps_gcc9:
  stage: build_dependencies
  image: gcc:9
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - conan install . --build missing
    - conan install . --build missing --s build_type=Debug
    - conan upload boost/* -r cps-artifactory --all
    - conan upload gtest/* -r cps-artifactory --all
    - conan upload redboltz-mqtt_cpp/* -r cps-artifactory --all
    - conan upload nlohmann_json/* -r cps-artifactory --all
  only:
      refs:
        - updateDependecies

build_gcc13:
  stage: build
  image: gcc:13
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - mkdir build && cd build
    - conan install .. --build missing
    - conan build ..
    - vonan install .. -s build_type=Debug
    - conan build .. -s build_type=Debug
  artifacts:
    paths:
      - build

build_gcc12:
  stage: build
  image: gcc:12
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - mkdir build && cd build
    - conan install .. --build missing
    - conan build ..
    - vonan install .. -s build_type=Debug
    - conan build .. -s build_type=Debug
  artifacts:
    paths:
      - build

build_gcc10:
  stage: build
  image: gcc:10
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - mkdir build && cd build
    - conan install .. --build missing
    - conan build ..
    - vonan install .. -s build_type=Debug
    - conan build .. -s build_type=Debug
  artifacts:
    paths:
      - build

build_gcc9:
  stage: build
  image: gcc:9
  before_script:
    - apt update && apt -y install make autoconf python3 python3-pip cmake
    - pip install --upgrade conan --break-system-packages
    - conan profile detect
    - conan remote add cps-artifactory http://131.246.211.170:8081/artifactory/api/conan/conan
    - conan remote login -p $ARTIFACTORY_TOKEN cps-artifactory gitlab_runner
  script:
    - mkdir build && cd build
    - conan install .. --build missing
    - conan build ..
    - vonan install .. -s build_type=Debug
    - conan build .. -s build_type=Debug
  artifacts:
    paths:
      - build



# run tests using the binary built before
test:
  stage: test
  script:
    - ./runmytests.sh

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  only:
    refs:
      - main
      - tags
